Change the format of the error message for NameError
We've discussed this internally and decided to make the following change:

Before:

    head :001 > require 'did_you_mean'; group_path = 1; groups_path = 1
    head :002 > group_paht
    NameError: undefined local variable or method `group_paht' for main:Object

        Did you mean? group_path
                      groups_path

            from (irb):1
            from /usr/local/rvm/rubies/ruby-head/bin/irb:11:in `<main>'
    head :003 >

After:

    head :001 > require 'did_you_mean'; group_path = 1; groups_path = 1
    head :002 > group_paht
    NameError: undefined local variable or method `group_paht' for main:Object
    Did you mean?  group_path
                   groups_path
            from (irb):1
            from /usr/local/rvm/rubies/ruby-head/bin/irb:11:in `<main>'
    head :003 >