Add an extra feature that shouldn't be used in production
This adds the ability to correct a mistyped instance variable name:

    require 'did_you_mean/extra_features'

    @number = 1
    @nubmer.zero?
    # => NoMethodError: undefined method `zero?' for nil:NilClass
    #
    #    Did you mean? @number
    #

This implementation uses TracePoint which is not stable yet (also see: https://bugs.ruby-lang.org/issues/11667), thus it should only be used in development. From this point, any feature that should only be used in development should go into `did_you_mean/extra_features/` dir.